### ISSUE TITLE
Extension does not limit my feed to my country only.

### ISSUE THREAD

**Issue by Ampa** [mountassir/ebay-search-extention#11]
Hi, thanks for the super useful extension.

One issue: my feed (https://www.ebay.co.uk/feed) is not limited to the UK (where i live) but also shows items from the USA (unwanted).

Is there any way to fix this, as it is pretty irritating!

Thanks.

**Comment by mountassir** [comment]
Hello, thank you for opening this request. I took a look at this and unfortunately the feed from eBay is not treated as a search, I don't see a way that this extention can help with this use case. Thanks!

**Comment by Ampa** [comment]
Thank you for investigating. A shame that it isn't possible.
