### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by peterG0RSQ** [mountassir/ebay-search-extention#5]
I suspect there may be an issue with this extension in firefox.

Recently firefox is only displaying one page of results.

After clearing cach cookies, and disabling AddBlocker+ I found that by disabling your extension restores the search to full multiple page results.

Not sure if this is the reason, but at moment solves the issue.

regards

peter

**Comment by mountassir** [comment]
Hi,

Thanks for reaching out! I am currently using the extension on Firefox and
I am seeing multiple pages in the search. Are you making a normal search on
eBay?

Thanks,
M

**Comment by peterG0RSQ** [comment]
Hi

 

Sorry it looks like issue is not with the extension after all.

 

Really weird, and quite erratic, but issue seems more to do with if I search from “saved searches”. This seems to be the main common denominator.

 

Thanks for quick response, and sorry for questioning the extension (which works great by the way J)

 

Regards

 

peter

**Comment by peterG0RSQ** [comment]
Hi

 

Worked out what is wrong. Someone on eBay community lead me to the issue.

 

Problem is with “UK Only” searches.

 

If I select default location I get full results.

 

Looks like eBay broke something again.

 

Thanks again for quick response and checking.

 

peter

**Comment by mountassir** [comment]
Thanks!
