### ISSUE TITLE
Advanced search problem

### ISSUE THREAD

**Issue by Namirred** [mountassir/ebay-search-extention#6]
Hi 

I tried to do an advanced search including filter by seller.  The page went into a load loop and I had to close the tab or disable the extension to complete the search, had me scratching my head for 5 mins.

I am using firefox 78.0.1(64-bit) on windows 10 pro.

Edit:  After looking further I have narrowed the problem to the location section.  By default it sets the search to worldwide, this appears to cause a conflict.  As soon as I changed it to United Kingdom the fault disappeared.  I hope that this will be a straightforward fix for you to save others the headache.  

Keep up the good work 
![Screenshot_2020-07-04 eBay search Advanced search](https://user-images.githubusercontent.com/49377674/86503797-6df33700-bda9-11ea-9c91-3580e7642c87.png)

**Comment by mountassir** [comment]
Interesting find, thanks for reporting this! 

It seems to be treating the advanced search menu as a search result because the url is under /sch/.

I will spend some time to fully understand how it ends up in a loop and deploy a fix, thanks.

**Comment by mountassir** [comment]
I have released a new version with the fix to both Chrome and Firefox.

**Comment by Namirred** [comment]
> I have released a new version with the fix to both Chrome and Firefox.

Working with my Firefox browser. Many thanks.
