### ISSUE TITLE
EU issue

### ISSUE THREAD

**Issue by joeorford** [mountassir/ebay-search-extention#9]
There is a small issue whereby in the UK, if you select only items in my continent region, it selects European Union only
This would be ok, but the UK is not in the EU anymore! So it doesn't show UK listings. Having it select Continental Europe would make it more useful

**Comment by derrickb** [comment]
@joeorford is correct. On ebay.co.uk, the location list no longer matches 1-for-1 with ebay.com
The _continent region_ option in the UK site is now "Continental Europe" and is the 5th item in the list.
However the extension will select "European Union" (see image) which excludes all search results in the UK.

![image](https://user-images.githubusercontent.com/1793769/133306499-961e2009-da43-4501-a47b-c2d6e23d8a3c.png)

**Comment by mountassir** [comment]
Thanks for reporting this! I can see the issue from my side as well, will take a look.

**Comment by mountassir** [comment]
Just submitted a new version 1.1.15 with a new option to select "continental region" items, it will take a few days before the update gets deployed to your browser, thanks!
